Fix issue 1043: ERROR:  container must be an array or object (#1046)
Fixed issue 1043 -

ERROR:  container must be an array or object

This was cause by agtype_access_operator not recognizing and
decoding a VLE path container.

Added regression tests.