Fix issue 395: ERROR: container is not an agtype array (#1039) (#1150)
Fixed issue 395 -

ERROR: container is not an agtype array

This was due to an incorrect order in checking for AGTV_NULL in
the collect aggregate transfer function: age_collect_aggtransfn

Added regression tests.